# Generated by Django 3.2.4 on 2021-06-19 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=datetime.datetime(2021, 6, 19, 4, 57, 20, 949237))),
                ('clientName', models.CharField(max_length=150)),
                ('projectName', models.CharField(max_length=150)),
                ('Skill', models.CharField(max_length=150)),
                ('projectDesc', models.CharField(max_length=500)),
            ],
        ),
    ]
